name: Minuto Seguro

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Ou outra versão LTS

      - name: Print Node and NPM versions
        run: |
          node -v
          npm -v

      - name: Clean Install
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install --omit=optional

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
 
            
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure